cabal-version: 3.0
name: himari
version: 0.1.0.0
synopsis: A standard library for Haskell as an alternative to rio
homepage: https://github.com/ncaq/himari
license: Apache-2.0
license-file: LICENSE
author: ncaq
maintainer: ncaq@ncaq.net
category: Control
build-type: Simple

common basic
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints
    -j

  default-language: GHC2024
  default-extensions:
    NoImplicitPrelude
    OverloadedStrings

  build-depends:
    base >=4.19.2.0 && <4.22

library
  import: basic
  hs-source-dirs: src
  -- cabal-gild: discover ./src
  exposed-modules: MyLib
