name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  gh-release-create:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: gh release create "${{ github.ref_name }}" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
